/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_HelloAndroid_HelloJNI */

#ifndef _Included_com_example_HelloAndroid_HelloJNI
#define _Included_com_example_HelloAndroid_HelloJNI
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_HelloAndroid_HelloJNI
 * Method:    stringFromJNI
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_example_HelloAndroid_HelloJNI_stringFromJNI
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
